apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapi
    environment: development
  name: api
  namespace: basta-2020
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - image: basta2020aks.azurecr.io/talk/api:0.1.0
          name: api
          envFrom:
            - configMapRef:
                name: basta-config
          volumeMounts:
            - name: write-file-target
              mountPath: /var/tt
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              port: 80
              path: /readiness
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              port: 80
              path: /liveness
            periodSeconds: 20
            timeoutSeconds: 1
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 400m
              memory: 128Mi
      volumes:
        - name: write-file-target
          persistentVolumeClaim:
            claimName: azure-files
