apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-files
  namespace: basta-2020
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
